# Generated by Django 4.2.2 on 2023-06-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dscrap', '0004_alter_document_docfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(default=None, null=True, upload_to='dscrap/images'),
        ),
    ]
