# Generated by Django 4.2.2 on 2023-06-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dscrap', '0005_alter_document_docfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.ImageField(default=None, upload_to='dscrap/images'),
        ),
    ]
