# Generated by Django 4.2.2 on 2023-06-26 19:53

from django.db import migrations, models
import dscrap.apps


class Migration(migrations.Migration):

    dependencies = [
        ('dscrap', '0007_rename_docfile_document_image_document_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='image',
            field=models.ImageField(upload_to=dscrap.apps.user_directory_path),
        ),
    ]
