# Generated by Django 4.2.2 on 2023-06-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dscrap', '0009_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
